steps:
# Build the image with docker
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-central1-docker.pkg.dev/robsite-assistant-prod/robsite-assistant-repo/robsite-assistant-image:$COMMIT_SHA .
  automapSubstitutions: true
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'us-central1-docker.pkg.dev/robsite-assistant-prod/robsite-assistant-repo/robsite-assistant-image:$COMMIT_SHA'  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'us-central1-docker.pkg.dev/robsite-assistant-prod/robsite-assistant-repo/robsite-assistant-image:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
# Imaage to use 
images:
- 'us-central1-docker.pkg.dev/robsite-assistant-prod/robsite-assistant-repo/robsite-assistant-image:$COMMIT_SHA'